### ISSUE TITLE
Where can I find results of your benchmark?

### ISSUE THREAD

**Issue by Alexander-Minyushkin** [miraclelinux/zabbix-benchmark#10]
Most interested in response times and hardware utilization depending on different workload and hardware (CPU, RAM, Disk)

**Comment by ashie** [comment]
We used this benchmark program for [MIRACLE-ZBX-2.0.3-NoSQL](https://github.com/miraclelinux/MIRACLE-ZBX-2.0.3-NoSQL) with
[HistoryGluon](https://github.com/miraclelinux/HistoryGluon).

Results:

* https://www.miraclelinux.com/labs/pdf/zabbix-read-performance
* https://www.miraclelinux.com/labs/pdf/zabbix-write-performance

**Comment by Alexander-Minyushkin** [comment]
Thank you!
